name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Remember to set up your Deno Deploy secret in the repository settings with the name DENO_DEPLOY_TOKEN
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "pixelfresh"
          entrypoint: "./main.ts"
